groups:
  - name: basic-alerts
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Target down: {{ $labels.job }}"
          description: "Instance appears down/unreachable. name={{ $labels.name }} private_ip={{ $labels.private_ip }}"
